---
- name: "Install Redis"
  apt:
    name: "redis-server"
    state: present

- name: "Redis replication stop"
  systemd:
    name: "redis-server"
    state: stopped
  ignore_errors: true

- name: Create Prereq Dir Redis Cluster
  file:
    path: "{{ item }}"
    state: directory
    owner: "redis"
    group: "redis"
  with_items:
    - '{{ redis_cluster_config_home }}'
    - '{{ redis_cluster_logs_home }}'
    - '{{ redis_cluster_data_home }}'
    - '{{ redis_cluster_runtime_home }}'

- name: "Copy redis-cluster-sentinel.conf to {{ redis_cluster_config_home }}"
  template:
    src: "templates/redis-cluster-sentinel.conf.j2"
    dest: "{{ redis_cluster_config_home }}/redis-sentinel.conf"
    owner: "redis"
    group: "redis"
    mode: 0644

- name: "Copy Redis replication Sentinel systemd unit file"
  template:
    src: "templates/redis-cluster-sentinel-systemd.j2"
    dest: "/etc/systemd/system/redis-sentinel.service"
    owner: "root"
    group:  "root"
    mode: 0644

- name: "Redis replication Sentinel restart"
  systemd:
    name: "redis-sentinel"
    state: restarted
    enabled: yes
    daemon_reload: yes